name: Push Nuget Package

on:
  workflow_dispatch:
  release:
    types: [released]
  workflow_run:
    workflows: ["Release New Version v1"]
    branches: [main]
    types:
      - completed

jobs:
  publish-project-to-artifact:
    name: Push Nuget Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Executable Solution
        run: |
          dotnet build ./src/cangulo.changelog.sln

# name: Push Nuget

# on:
#   workflow_dispatch:

# 1. Provide the version as input
# 2. Put the version in the cicd.json file
#
#

# jobs:
#   push-nuget:
#     runs-on: ubuntu-latest
#     name: Push Nuget
#     steps:
#       - uses: actions/checkout@v2
#       - name: Downloading cangulo.cicd
#         uses: cangulo/cangulo.cicd-gh-action@v0.0.1
#         with:
#           version: latest
#       - name: Pack Nuget Package
#         run: ./cangulo.cicd/cangulo.cicd --root . --target CreateReleaseNugetPackage
#       - name: Push Nuget Package
#         env:
#           NugetApiKey: ${{ secrets.NUGET_API_KEY }}
#         run: ./cangulo.cicd/cangulo.cicd --root . --target PushNugetPackages
