name: Execute UT

on:
  pull_request:
    paths:
      - "src/**"
      - "test/**"

jobs:
  execute-UT:
    runs-on: ubuntu-latest
    name: Execute UT
    steps:
      - uses: actions/checkout@v2
      - name: Downloading cangulo.cicd
        uses: cangulo/cangulo.cicd-gh-action@v0.0.1
        with:
          version: latest
      - name: Execute UT
        run: ./cangulo.cicd/cangulo.cicd --root . --target ExecuteUnitTests --verbosity verbose
