name: PR Merged to Main

on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  release-new-version:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Downloading cangulo.cicd
        uses: cangulo/cangulo.cicd-gh-action@v0.0.1
        with:
          version: latest
      - name: Calculate Next Release Number
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./cangulo.cicd/cangulo.cicd --root . --target CalculateNextReleaseNumber UpdateVersionInCICDFile UpdateChangelog UpdatePreReleaseVersionInCSProj GitPushReleaseFiles
      # - name: Update Version In CICD File, Changelog and csproj file
      #   run: ./cangulo.cicd/cangulo.cicd --root . --target UpdateVersionInCICDFile UpdateChangelog UpdatePreReleaseVersionInCSProj GitPushReleaseFiles
      # - name: Pushing changes
      #   run: ./cangulo.cicd/cangulo.cicd --root . --target GitPushReleaseFiles
      - name: Create the New Release
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./cangulo.cicd/cangulo.cicd --root . --target CreateNewRelease --skip ListCommitsInThisPR
      - name: Pack Nuget Package
        run: ./cangulo.cicd/cangulo.cicd --root . --target CreateReleaseNugetPackage
      - name: Push Nuget Package
        env:
          NugetApiKey: ${{ secrets.NUGET_API_KEY }}
        run: ./cangulo.cicd/cangulo.cicd --root . --target PushNugetPackages
