name: PR Validate Commits

on:
  pull_request:

jobs:
  validate-conventional-commits:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Downloading cangulo.cicd
        uses: cangulo/cangulo.cicd-gh-action@v0.0.1
        with:
          version: latest
      - name: Validate Conventional Commits
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./cangulo.cicd/cangulo.cicd --root . --target VerifyAllCommitsAreConventionalInThisPR
